CREATE TABLE IF NOT EXISTS USERS
(
user_id CHAR(36) PRIMARY KEY,
name VARCHAR(30) NOT NULL,
surname VARCHAR(50) NOT NULL,
birth_date TIMESTAMP NOT NULL,
inn VARCHAR(12) NOT NULL,
snils VARCHAR(11) NOT NULL,
pass_number VARCHAR(11) NOT NULL UNIQUE,
login VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL
);
