CREATE TABLE IF NOT EXISTS USERS
(
id BIGSERIAL PRIMARY KEY,
name VARCHAR(30) NOT NULL,
surname VARCHAR(50) NOT NULL,
birth_date TIMESTAMP NOT NULL,
inn VARCHAR(12) UNIQUE NOT NULL,
snils VARCHAR(11) UNIQUE NOT NULL,
pass_number VARCHAR(11) NOT NULL UNIQUE,
login VARCHAR(50) UNIQUE NOT NULL,
password VARCHAR(50) NOT NULL
);

--rollback DROP TABLE users;
